language: java
jdk:
  - oraclejdk7
notifications:
  email:
    recipients:
      - cibuilds@duracloud.org
    on_success: change
    on_failure: always
install:
  - mvn install -DskipTests -DskipDeploy
script:
  - mvn test -DskipIntTests
